[package]
name = "transitive_path_dep"
version = "0.1.0"
authors = ["konstin <konstin@mailbox.org>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
