[package]
authors = ["konstin <konstin@mailbox.org>"]
name = "pyo3-mixed-submodule"
version = "2.1.3"
description = "Implements a dummy function combining rust and python"
readme = "README.md"
edition = "2021"

[dependencies]
pyo3 = "0.27.0"

[lib]
name = "pyo3_mixed_submodule"
crate-type = ["cdylib"]
