# Workaround to bootstrap maturin on non-manylinux platforms
[build-system]
requires = ["setuptools~=53.0.0", "wheel~=0.36.2", "toml~=0.10.2"]
build-backend = "setuptools.build_meta"

[project]
name = "maturin"
requires-python = ">=3.6"
classifiers = [
    "Topic :: Software Development :: Build Tools",
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = ["toml~=0.10.2"]

[project.urls]
"Source Code" = "https://github.com/PyO3/maturin"
Issues = "https://github.com/PyO3/maturin/issues"
Documentation = "https://maturin.rs"
Changelog = "https://maturin.rs/changelog.html"

[tool.maturin]
bindings = "bin"

[tool.black]
target_version = ['py36']
extend-exclude = '''
# Ignore cargo-generate templates
^/src/templates
'''
