[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "bin-with-python-module"
version = "0.1.0"
requires-python = ">=3.8"

[tool.maturin]
bindings = "bin"
module-name = "bin_with_python_module"
