[workspace]
members = [
  "generic_lib",
  "python"
]

[workspace.package]
version = "0.1.0"

[workspace.dependencies]
cfg-if = "1.0.0"
libc = { version = "0.2", features = ["std"] }
rand = "0.8"
generic_lib = { path = "generic_lib" }
