[package]
name = "cargo-mock"
version = "0.1.0"
authors = ["konstin <konstin@mailbox.org>"]
edition = "2021"

[[bin]]
name = "cargo"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.38"
cargo_metadata = "0.12.3"
serde_json = "1.0.62"
