[package]
name = "cffi-pure"
version = "0.1.0"
authors = ["Armin Ronacher <armin.ronacher@active-4.com>"]
edition = "2018"

[lib]
name = "cffi_pure"
crate-type = ["cdylib"]

[package.metadata.maturin]
requires-dist = ["cffi"]