[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "pyo3-mixed-src"
readme = "README.md"
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Rust"
]
requires-python = ">=3.7"
dynamic = ["version"]

[project.scripts]
get_42 = "pyo3_mixed_src:get_42"

[tool.maturin]
python-packages = ["pyo3_mixed_src", "tests"]
