[package]
name = "readme_py"
version = "0.2.0"
edition = "2021"
readme = "README.md"
publish = false

[lib]
name = "readme"
crate-type = ["cdylib"]

[dependencies]
readme-rs = { path = "../readme-rs" }
pyo3 = "0.27.0"
