[package]
name = "a"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
uniffi = "0.28.0"
b = { path = "../b" }

[build-dependencies]
uniffi = { version = "0.28.0", features = ["build"] }
