[package]
name = "path_dep_with_root"
version = "0.1.0"
description = "path dep"
edition = "2021"

[lib]
name = "path_dep_with_root"
crate-type = ["lib", "cdylib"]

[dependencies]
top_level = { path = "../" }
once_cell = "1"
pyo3 = { version = "0.22.5", features = ["abi3", "abi3-py310", "extension-module"] }
