[package]
name = "cffi-mixed"
version = "0.1.0"
authors = ["Armin Ronacher <armin.ronacher@active-4.com>"]
edition = "2018"

[lib]
name = "cffi_mixed"
crate-type = ["cdylib"]

[package.metadata.maturin]
requires-dist = ["cffi"]
