[package]
name = "uniffi-pure-proc-macro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "uniffi_pure_proc_macro"
crate-type = ["cdylib"]

[[bin]]
name = "uniffi-bindgen"
path = "uniffi-bindgen.rs"
required-features = ["bindgen"]

[features]
bindgen = ["uniffi/cli"]

[dependencies]
uniffi = "0.28.0"

[build-dependencies]
uniffi = { version = "0.28.0", features = ["build"] }
