[package]
name = "sdist_with_path_dep"
version = "0.1.0"
authors = ["konstin <konstin@mailbox.org>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.26.0", features = ["extension-module"] }
some_path_dep = { path = "../some_path_dep" }
